### ISSUE TITLE
感谢作者

### ISSUE THREAD

**Issue by KainingYing** [lyy1994/awesome-data-contamination#1]
您好，@lyy1994，

我最近也在看相关的工作，看到你整理得这么多，非常感谢你的分享。

请问这个list是几乎所有的数据污染相关的工作了吗，这个邻域感觉的关注度感觉还是不够哈。

**Comment by lyy1994** [comment]
感谢您的关注！这个列表应该是比较全面覆盖了数据污染相关工作了，因为里面的论文的引用和参考文献我都有大致检查过，遗漏的相关文献应该比较少。

这个领域我感觉关注度还是有的，但可能这个领域太难了，数据污染这个事情也提出好几年了，在不公开训练数据集的情况下检测污染可利用的信息太少了，也就最近有两篇相关工作，而防止污染这个就更难了，除了高成本地构造新数据目前还没其他解法。

不过数据污染的关注度应该没有想象的高，因为即使你能检测出污染又能怎么样呢？很多任务就那么几个经典数据集，污染了难道就不用吗？自己标注一个新的成本太高了，而且质量也需要同行评审和社区的时间检验，导致这个事情有点像房间里的大象。
