### ISSUE TITLE
Great collection.

### ISSUE THREAD

**Issue by liyucheng09** [lyy1994/awesome-data-contamination#2]
感谢作者整理！
今天突然冒出来个idea说为啥不弄个awesome-data-contamination，结果一搜发现兄弟已经做的那么完善了。

期待以后交流。

**Comment by lyy1994** [comment]
:handshake:感谢关注！有机会多多交流！

**Comment by KainingYing** [comment]
有没有交流群，可以讨论一下的，对这个方向很感兴趣

**Comment by lyy1994** [comment]
应该没有建群的
