### ISSUE TITLE
Kindly request the inclusion

### ISSUE THREAD

**Issue by ShangQingTu** [lyy1994/awesome-data-contamination#4]
Thank you for this great paper collection! It will be my pleasure if my work can be included in the repo; thanks!

<!DOCTYPE html><figure class="md-table-fig" cid="n403" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;">
Title | Paper | Code | Venue | Classification | Model | Comment
-- | -- | -- | -- | -- | -- | --
DICE: Detecting In-distribution Contamination in LLM's Fine-tuning Phase for Math Reasoning | https://arxiv.org/abs/2406.04197 | https://github.com/THU-KEG/DICE | arXiv'24 |[![img](https://camo.githubusercontent.com/3ccb33f61b5d402559580be2d20d05836940a69f00fbd9ed87cb7f79294ddf02/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f52656163746976652d677265656e)](https://camo.githubusercontent.com/3ccb33f61b5d402559580be2d20d05836940a69f00fbd9ed87cb7f79294ddf02/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f52656163746976652d677265656e) [![img](https://camo.githubusercontent.com/f01f34861d4c28663f1add4b3d392a7879b148eb1d633ad56ebb962b1e1eafab/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f416e616c797369732d62726f776e)](https://camo.githubusercontent.com/f01f34861d4c28663f1add4b3d392a7879b148eb1d633ad56ebb962b1e1eafab/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f416e616c797369732d62726f776e)[![img](https://camo.githubusercontent.com/d448bd40d73d47760a38423a5a8f6aa3ff2417fcefca953302b433ecede58d28/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f546f6f6c2d707572706c65)](https://camo.githubusercontent.com/d448bd40d73d47760a38423a5a8f6aa3ff2417fcefca953302b433ecede58d28/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f546f6f6c2d707572706c65)  | LLM | A novel contamination detection method  which leverages the internal states of LLMs to detect data contamination in fine-tune stage for math reasoning.
KoLA: Carefully Benchmarking World Knowledge of Large Language Models | https://openreview.net/forum?id=AqN23oqraW | https://kola.xlore.cn/ | ICLR'24 | [![img](https://camo.githubusercontent.com/7565de855159c52c2936a878e34ec8d0149878898cf3b1c8980e27e71ef152d2/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f50726576656e7461746976652d626c7565)](https://camo.githubusercontent.com/7565de855159c52c2936a878e34ec8d0149878898cf3b1c8980e27e71ef152d2/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f50726576656e7461746976652d626c7565) [![](https://camo.githubusercontent.com/d735d27234a75fe14a034e0ca04bb2f9841cbddd0c639d55f4a12f8466e231ca/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f446174617365742d6f72616e6765)](https://camo.githubusercontent.com/d735d27234a75fe14a034e0ca04bb2f9841cbddd0c639d55f4a12f8466e231ca/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f446174617365742d6f72616e6765) | LLM | A carefully designed evolving benchmark for evaluating LLMs' world knowledge. KoLA benchmark is evolving so that it can avoid the data contamination issue.

</figure><p cid="n132" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;"></p><br class="Apple-interchange-newline">

**Comment by lyy1994** [comment]
Sorry for the late reply. I have added your work to the paper list. Thanks for your suggestion!

**Comment by ShangQingTu** [comment]
Thank you!
